meta_product_name: "Dream Cocktails"
meta_title: "Dream Cocktails - Find your dream cocktail !"
meta_description: "You can find here more than 600 cocktails! Enough to spice up your parties and make great taste discoveries!"
meta_image: "cover.png" # should exist in `app/assets/images/`
